Preapps 4189
Zimbra/userguide pull request #2
Opened 2020-03-23 10:21 UTC by abyshukla

@mogsdad Please review

2020-03-24 12:02 UTC, mogsdad requested changes

2020-03-24 12:02 UTC, mogsdad commented on calendar-manage-calendars.adoc
> +View, edit, add and remove:: Users can view and edit all appointments, *except* private ones. They can also add and delete events (*except* private events) from your calendar.
Use the [Oxford comma](https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/) to avoid misunderstandings. (e.g., is "add and remove" one right, or two?)

If you revert that change, this line will remain untouched... but I'll say this anyway: If you're changing a line that isn't following the "one sentence per line, one line per sentence" rule, fix that while you're there.

2020-03-24 12:02 UTC, mogsdad commented on calendar-manage-events.adoc
> +A reminder box may list multiple events. To turn off _all_ reminders, click *Dismiss All*.
That's two sentences now, so two lines.

2020-03-24 12:02 UTC, mogsdad commented on mail-overview.adoc
> +// NOTE: If you are using the {product-name} desktop application, you may see a **Local Storage** option below folders. <<mail-localstorage.adoc#_local_storage, Local Storage>> section details this f
The desktop app is not part of Zimbra 9, and should not appear in documentation for that release.

2020-03-24 12:02 UTC, mogsdad commented on managing-profiles.adoc
> +. Click image:images/graphics/rotate_left.svg[counter clockwise arrow icon, width=20] or image:images/graphics/rotate_right.svg[clockwise arrow icon, width=20] to rotate the picture 90 degrees left o
Suggestion: "A quarter turn" instead of "90 degrees", because humans.

2020-03-24 12:02 UTC, mogsdad commented on user-guide.adoc
>  :copyright-year: 2020
This top documentation file is "user-guide.adoc", but the README indicates that `index.adoc` should be used to produce the asciidoctor output.

The README should be updated, or this file renamed.

2020-03-26 05:01 UTC, abyshukla commented on calendar-manage-calendars.adoc
> +View, edit, add and remove:: Users can view and edit all appointments, *except* private ones. They can also add and delete events (*except* private events) from your calendar.
Adding and removing are two different options and hence I separated them with a comma.
However, in the app, it reads 'add and remove' - without a comma. Which one should be used?

2020-03-27 14:38 UTC, merged